const UPDATE_SEARCH_DATA = 'UPDATE_SEARCH_DATA';
const START_SEARCH = 'START_SEARCH';
const END_SEARCH = 'END_SEARCH';

const SET_ROOM_ID = 'SET_ROOM_ID';

const SET_PLAYBACK = 'SET_PLAYBACK';
const UPDATE_PLAYBACK = 'UPDATE_PLAYBACK';

export {
  UPDATE_SEARCH_DATA,
  START_SEARCH,
  END_SEARCH,
  SET_ROOM_ID,
  SET_PLAYBACK,
  UPDATE_PLAYBACK,
};
